import { meta, shopify, starbucks, tesla, nuseum, hero, siesta, net, python, springboot, vue } from "../assets/images";
import {
    angular,
    car,
    contact,
    css,
    dotnet,
    estate,
    express,
    git,
    github,
    html,
    javascript,
    linkedin,
    mongodb,
    motion,
    mui,
    nextjs,
    nodejs,
    pricewise,
    react,
    redux,
    sass,
    snapgram,
    summiz,
    swift,
    tailwindcss,
    threads,
    typescript
} from "../assets/icons";

export const skills = [
    {
        imageUrl: react,
        name: "React",
        type: "Frontend",
    },
    {
        imageUrl: vue,
        name: "Vue.js",
        type: "Frontend",
    },
    {
        imageUrl: javascript,
        name: "JavaScript",
        type: "Frontend",
    },
    {
        imageUrl: typescript,
        name: "TypeScript",
        type: "Frontend",
    },
    {
        imageUrl: tailwindcss,
        name: "Tailwind CSS",
        type: "Frontend",
    },
    {
        imageUrl: css,
        name: "CSS",
        type: "Frontend",
    },
    {
        imageUrl: html,
        name: "HTML",
        type: "Frontend",
    },
    {
        imageUrl: python,
        name: "Python",
        type: "Backend",
    },
    {
        imageUrl: springboot,
        name: "Spring Boot",
        type: "Backend",
    },
    {
        imageUrl: nodejs,
        name: "Node.js",
        type: "Backend",
    },
    {
        imageUrl: express,
        name: "Express",
        type: "Backend",
    },
    {
        imageUrl: mongodb,
        name: "MongoDB",
        type: "Database",
    },
    {
        imageUrl: git,
        name: "Git",
        type: "Version Control",
    },
    {
        imageUrl: github,
        name: "GitHub",
        type: "Version Control",
    },
    {
        imageUrl: javascript,
        name: "Three.js",
        type: "3D Graphics",
    },
    {
        imageUrl: mui,
        name: "Material-UI",
        type: "Frontend",
    },
    {
        imageUrl: nextjs,
        name: "Next.js",
        type: "Frontend",
    },
    {
        imageUrl: swift,
        name: "Swift",
        type: "Mobile Development",
    },
    {
        imageUrl: angular,
        name: "Angular",
        type: "Frontend",
    },
    {
        imageUrl: dotnet,
        name: ".NET",
        type: "Backend",
    }
];

export const experiences = [
    {
        title: "Software Developer Intern",
        company_name: "Auckland Bioengineering Institute",
        icon: hero,
        iconBg: "#accbe1",
        date: "Jul 2025 – Current",
        points: [
            "Designed and implemented a data-driven 3D medical model visualization platform with JSON-based dynamic content loading.",
            "Developed a reusable VTK 3D model loader based on Three.js to support further extension and scalability.",
            "Utilised AI-assisted tools to accelerate feature iteration while maintaining accuracy through git version control and code review.",
            "Built a responsive cross-platform UI using Vue framework with TailwindCSS, ensuring consistent user experience across all devices.",
            "Established comprehensive project documentation using Sphinx and published through ReadTheDocs to support reproducibility and team onboarding.",
            "Configured an automated CI/CD pipeline with GitHub Actions and GitHub Pages deployment, enhancing development efficiency and team collaboration.",
            "Applied Agile practices through weekly meetings to share progress, adjust priorities, and track issues for better collaboration and responsiveness."
        ],
    },
    {
        title: "Database Specialist Intern",
        company_name: "NUSEUM (AI-driven nutrition suggestions)",
        icon: nuseum,
        iconBg: "#fbc3bc",
        date: "Dec 2024 – Feb 2025",
        points: [
            "Collaborated with a cross-national team to synchronize database updates, ensuring data consistency and efficient version control.",
            "Structured and optimized data types to support AI model training, improving the quality and usability of training datasets.",
            "Designed the database for progressive data input, enabling gradual expansion from simple to complex data while maintaining scalability and integrity.",
            "Implemented best practices in database management to support collaborative AI development and streamline workflow."
        ],
    },
    {
        title: "Full-Stack Developer Intern",
        company_name: "JumBox",
        icon: hero,
        iconBg: "#b7e4c7",
        date: "Oct 2020 – Jun 2021",
        points: [
            "Developed reusable Vue.js components to enable global state management and streamline data communication across the application.",
            "Built a QR code–based user sharing feature with posters generated by Canvas.js APIs, leading to 3,000+ users in a single day for a stress-relief application.",
            "Designed responsive layouts to ensure seamless performance across devices.",
            "Wrote and executed unit tests with JUnit to verify backend functionality and improve reliability.",
            "Collaborated in an Agile environment using Jira for sprint planning, reporting to project supervisors, and coordinating with design and client teams for timely delivery.",
            "Leveraged Git for version control and peer code reviews, ensuring high-quality iterative development."
        ],
    },
    {
        title: "Python Tutor (Volunteer)",
        company_name: "Teach Girls Coding Program",
        icon: hero,
        iconBg: "#b7e4c7",
        date: "Sep 2021 – Mar 2022",
        points: [
            "Mentored over 30 women from diverse industries, helping them start their journey into Python programming.",
            "Delivered personalized coding lessons, tailored to different backgrounds and learning paces.",
            "Created instructional materials and hands-on exercises to reinforce learning and build confidence."
        ],
    },
];

export const socialLinks = [
    {
        name: 'Contact',
        iconUrl: contact,
        link: '/contact',
    },
    {
        name: 'GitHub',
        iconUrl: github,
        link: 'https://github.com/Chenxue3',
    },
    {
        name: 'LinkedIn',
        iconUrl: linkedin,
        link: 'https://www.linkedin.com/in/xueshan-chen-48a0b82ba/',
    }
];

export const projects = [
    {
        iconUrl: pricewise,
        theme: 'btn-back-red',
        name: 'Beef Demand Insights',
        description: 'Data-driven web application for analyzing beef market trends and demand patterns. Built with modern web technologies to provide real-time insights for agricultural stakeholders.',
        link: 'https://sff-demo-zoea.vercel.app/',
    },
    {
        iconUrl: pricewise,
        theme: 'btn-back-blue',
        name: 'PicBed: My Self Image Hosting Service',
        description: 'Self-hosted image hosting service built with modern web technologies to provide a secure and reliable way to store and share images, using ASP.NET Core and SQLite',
        link: 'https://picbed.onrender.com/',
    },
    {
        iconUrl: threads,
        theme: 'btn-back-green',
        name: 'GenGPT-X',
        description: 'Web application using Java, Spring Boot, JavaScript, Vue, and MySQL to address the lack of user-friendly Goal-Plan-Tree generators for agent research. Improved the generator structure and applied it to real-world scenarios.',
        link: 'https://github.com/Chenxue3/gen-gpt-x',
        videoUrl: 'https://youtu.be/i_ZFhoxsFcM',
    },
    {
        iconUrl: snapgram,
        theme: 'btn-back-pink',
        name: 'Speaking Events Daily',
        description: 'Automated system that fetches and parses event information about "Speaking Group" events, then sends daily email notifications with details to specified recipients. Fully automated using GitHub Actions.',
        link: 'https://github.com/Chenxue3/speaking-events-daily',
    },
    {
        iconUrl: car,
        theme: 'btn-back-blue',
        name: 'Pregnancy Care App',
        description: 'Comprehensive pregnancy support application designed for Aotearoa New Zealand. Built with Nuxt.js, Vue.js, and Three.js to provide interactive 3D visualizations and trusted health information for expectant mothers and their whānau.',
        link: 'https://virtualpregnancy.github.io/pregnancy-app/',
    },
];