/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Brandon Westlake (https://sketchfab.com/dr.badass2142)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/retro-computer-setup-free-82eaf2047e0447a1bfea22482f1d1404
Title: Retro Computer Setup (FREE)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import computer from '../assets/3d/computer.glb'

export default function Computer(props) {
    // load the model
  const { nodes, materials } = useGLTF(computer)
  const computerRef = useRef();
  // set up the rotation
  useFrame(() => {
    // auto-rotation
    computerRef.current.rotation.y += 0.0005;
  })


//   mouse movement
const handleMouseMove = (event) => {
    // if the left button is clicked, rotate the model
  if (event.buttons === 1){
    computerRef.current.rotation.y += event.movementX * 0.01;//the rotation is based on the mouse movement
  }
}
  
  return (
    <group {...props} dispose={null}
    ref={computerRef} //ref the model
    onPointerMove={handleMouseMove} //handle the mouse movement
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.retro_computer_setup_retro_computer_setup_Mat_0.geometry}
        material={materials.retro_computer_setup_Mat}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/computer.glb')
